name: Unit Tests

on:
  push:
    branches: [ StarterCodeDrafts ]
  pull_request:
    branches: [ StarterCodeDrafts ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          cd Budget-Tracker---CSE-110-Lab-4/client
          npm install
      - name: Unit Test
        run: |
          cd Budget-Tracker---CSE-110-Lab-4/client
          npm test
